/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as IdeaBoardRouteImport } from './routes/idea-board'
import { Route as ExperimentCardRouteImport } from './routes/experiment-card'
import { Route as CommitmentRouteImport } from './routes/commitment'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as IndexRouteImport } from './routes/index'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeaBoardRoute = IdeaBoardRouteImport.update({
  id: '/idea-board',
  path: '/idea-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentCardRoute = ExperimentCardRouteImport.update({
  id: '/experiment-card',
  path: '/experiment-card',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitmentRoute = CommitmentRouteImport.update({
  id: '/commitment',
  path: '/commitment',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/commitment': typeof CommitmentRoute
  '/experiment-card': typeof ExperimentCardRoute
  '/idea-board': typeof IdeaBoardRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/commitment': typeof CommitmentRoute
  '/experiment-card': typeof ExperimentCardRoute
  '/idea-board': typeof IdeaBoardRoute
  '/team': typeof TeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/commitment': typeof CommitmentRoute
  '/experiment-card': typeof ExperimentCardRoute
  '/idea-board': typeof IdeaBoardRoute
  '/team': typeof TeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/commitment'
    | '/experiment-card'
    | '/idea-board'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/commitment'
    | '/experiment-card'
    | '/idea-board'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/commitment'
    | '/experiment-card'
    | '/idea-board'
    | '/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  CommitmentRoute: typeof CommitmentRoute
  ExperimentCardRoute: typeof ExperimentCardRoute
  IdeaBoardRoute: typeof IdeaBoardRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idea-board': {
      id: '/idea-board'
      path: '/idea-board'
      fullPath: '/idea-board'
      preLoaderRoute: typeof IdeaBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiment-card': {
      id: '/experiment-card'
      path: '/experiment-card'
      fullPath: '/experiment-card'
      preLoaderRoute: typeof ExperimentCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commitment': {
      id: '/commitment'
      path: '/commitment'
      fullPath: '/commitment'
      preLoaderRoute: typeof CommitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  CommitmentRoute: CommitmentRoute,
  ExperimentCardRoute: ExperimentCardRoute,
  IdeaBoardRoute: IdeaBoardRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
